name: "Nickolus Justice"
description: "Rants, mostly about software"

author: "Nickolus Justice"

url: "http://www.nickolusjustice.com"
baseUrl: ""

markdown: rdiscount
permalink: :year/:month/:title.html
pygments: true
